# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window3(object):
    def setupUi(self, Window3):
        Window3.setObjectName("Window3")
        Window3.resize(600, 450)
        self.label = QtWidgets.QLabel(Window3)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.buttonMenu3 = QtWidgets.QPushButton(Window3)
        self.buttonMenu3.setGeometry(QtCore.QRect(0, 0, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(15)
        self.buttonMenu3.setFont(font)
        self.buttonMenu3.setStyleSheet("color: rgb(250, 250, 250);\n"
"background-color: rgb(0, 0, 0);")
        self.buttonMenu3.setObjectName("buttonMenu3")
        self.buttonGraph1 = QtWidgets.QPushButton(Window3)
        self.buttonGraph1.setGeometry(QtCore.QRect(200, 190, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(11)
        self.buttonGraph1.setFont(font)
        self.buttonGraph1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.buttonGraph1.setObjectName("buttonGraph1")
        self.buttonGraph2 = QtWidgets.QPushButton(Window3)
        self.buttonGraph2.setGeometry(QtCore.QRect(200, 240, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(11)
        self.buttonGraph2.setFont(font)
        self.buttonGraph2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.buttonGraph2.setObjectName("buttonGraph2")

        self.retranslateUi(Window3)
        QtCore.QMetaObject.connectSlotsByName(Window3)

    def retranslateUi(self, Window3):
        _translate = QtCore.QCoreApplication.translate
        Window3.setWindowTitle(_translate("Window3", "Dialog"))
        self.label.setText(_translate("Window3", "Графіки"))
        self.buttonMenu3.setText(_translate("Window3", "Меню"))
        self.buttonGraph1.setText(_translate("Window3", "Графік товарообміну"))
        self.buttonGraph2.setText(_translate("Window3", "Графік чисельності"))
