# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window2(object):
    def setupUi(self, Window2):
        Window2.setObjectName("Window2")
        Window2.resize(600, 450)
        self.label = QtWidgets.QLabel(Window2)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.table_2 = QtWidgets.QLabel(Window2)
        self.table_2.setGeometry(QtCore.QRect(0, 50, 600, 400))
        self.table_2.setText("")
        self.table_2.setAlignment(QtCore.Qt.AlignCenter)
        self.table_2.setObjectName("table_2")
        self.buttonMenu_2 = QtWidgets.QPushButton(Window2)
        self.buttonMenu_2.setGeometry(QtCore.QRect(0, 0, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(15)
        self.buttonMenu_2.setFont(font)
        self.buttonMenu_2.setStyleSheet("color: rgb(250, 250, 250);\n"
"background-color: rgb(0, 0, 0);")
        self.buttonMenu_2.setObjectName("buttonMenu_2")

        self.retranslateUi(Window2)
        QtCore.QMetaObject.connectSlotsByName(Window2)

    def retranslateUi(self, Window2):
        _translate = QtCore.QCoreApplication.translate
        Window2.setWindowTitle(_translate("Window2", "Dialog"))
        self.label.setText(_translate("Window2", "Довідник магазинів"))
        self.buttonMenu_2.setText(_translate("Window2", "Меню"))
